package frames;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import com.jfoenix.controls.JFXDatePicker;

import javafx.scene.control.TableColumn;

public class ManageMissionController1 {
	@FXML
	private TableView tablemission;
	@FXML
	private TableColumn titleC;
	@FXML
	private TableColumn descriptionC;
	@FXML
	private TableColumn fieldC;
	@FXML
	private TableColumn startC;
	@FXML
	private TableColumn endC;
	@FXML
	private TableColumn missiontypeC;
	@FXML
	private TableColumn stateC;
	@FXML
	private TableColumn localC;
	@FXML
	private TableColumn priceC;
	@FXML
	private TableColumn skillsC;
	@FXML
	private Button Update;
	@FXML
	private JFXButton jfx;
	@FXML
	private JFXDatePicker date;

	// Event Listener on Button[#Update].onAction
	@FXML
	public void UpdateMission(ActionEvent event) {
		// TODO Autogenerated
	}
}
